// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu5l0U6oMnC04mc7HYKOXteZftsKkKIwY',
    appId: '1:440904080620:web:1d91269285aebf66b519c9',
    messagingSenderId: '440904080620',
    projectId: 'yutop-444a3',
    authDomain: 'yutop-444a3.firebaseapp.com',
    storageBucket: 'yutop-444a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_lzAMkCiz5FDGOh4EfpgqrlrNwFicKqM',
    appId: '1:440904080620:android:be663fb15f1a4d52b519c9',
    messagingSenderId: '440904080620',
    projectId: 'yutop-444a3',
    storageBucket: 'yutop-444a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTLypRqIESgFp_YFfOrNY2DhJr4mqN-GM',
    appId: '1:440904080620:ios:45f123245db876e1b519c9',
    messagingSenderId: '440904080620',
    projectId: 'yutop-444a3',
    storageBucket: 'yutop-444a3.appspot.com',
    iosClientId: '440904080620-3m30rrntus6tmkmqh6nuph7lf5habid4.apps.googleusercontent.com',
    iosBundleId: 'com.example.youtube',
  );
}
